name: CI devops 2025

on:
  push:
    branches: [main, develop]  # ✅ Exécute le pipeline sur les branches main et develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04

    steps:
      # ✅ Récupère le code du repo
      - uses: actions/checkout@v4

      # ✅ Configure Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # ✅ Lance la commande Maven pour build + test
      - name: Build and test with Maven
        run: mvn clean verify
