name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Récupère le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configure Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Étape 3 : Build + test
      - name: Build and test with Maven
        run: mvn clean verify --file .\simple-api\pom.xml
